export const FORMULARIO_ALERTA = 'FORMULARIO_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR ='REGISTRO_ERROR';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR ='LOGIN_ERROR';
